apiVersion: ENC[AES256_GCM,data:CWQ=,iv:OJq+0JDaakvl+MfVuYPkP53Qjsgo19eIxM1o9P45fHc=,tag:PQnYp/goYRNW2PcfaUfDoA==,type:str]
kind: ENC[AES256_GCM,data:fDR/0e7t,iv:+r1UHZFCXrIIPG3QLBhgZ5sBx9wTK83UXhU4BNSe6D0=,tag:m3rCiyNs6cG84oEujtZsPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:N7ia+pTpx8lAUcY=,iv:6kXIX8rV/e6tV0sZuX8oTgPEgDoFB0iHvIN1OZm7Foc=,tag:J9o/SD2zMkD3ATDbDLN1AA==,type:str]
    namespace: ENC[AES256_GCM,data:qmalaUmCyg==,iv:ra81BATGhPTMVFD6AwvLNg4Q4mYgHYOPWou8T0wO164=,tag:20r7ratvC2Y9k66JeSDx+g==,type:str]
type: ENC[AES256_GCM,data:nri/84xS,iv:K2aQTpKMkymn1qfjzcDSuDQXiMtZDyFrCBrQjVO126U=,tag:0sNwO5uei7U/4T/fCEInYg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:XtLDAlBuXa+gJx+AQJX+e3p/,iv:3KPUnqvkMDOivKskwvOZte2jxcBQ0K9jJJJwIYFQWRE=,tag:9xCLQBleTBuqpgUoy/eGPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnODRpNitkZXorby9HbTBR
            SFk1WHd5SkdpQXNVNFpXWkhqYWFpbzNZMFQwCkpTbUp4VUMxSXNBVE5zNm8yMGZw
            Q3FLZm5ZMUpjUlpGMi9YWWpQUk56S00KLS0tIDFnY2JmRUEyeWd4MXp1UU4vMzVu
            dGFCNUhENUFVWUpsRUUxMDlUdGsreEkKL91XUhTkPUUpZ2lOh+aC5JMBJ8SC095K
            qirTaQjoGReULnlqIoP3E232vlUhh/aT87bohx5JtVxzxRhBgIpuwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y9prq8uj357x5kcd0w4s3m9cttrs9uavx2d75cnhzucgmfgyya0stsc6sw
    lastmodified: "2026-06-18T17:35:40Z"
    mac: ENC[AES256_GCM,data:FgXLRyTFc3nm8VQkTqyzwxizPJEHt9EgzUN1CixGhBWKuRYXDDQwzTRbyfcRTecnvugeGp1Ck5YM1WFpMAQpV1OAPeFVopmwhgd2Xxj0+iQH0mp3dTF4sGHOwxanwYU1x/Ygts84jmmWuDVACTGqvlWlToXqTjzNTfX1WD+64Z8=,iv:bkmDX3MzRSK7juKfv5jMYwXyN7y91o5h/BH4q33QevQ=,tag:AlKYxXz6dTwDDAdWu8f8fg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
